### PR TITLE
Add .ruby-version to .gitignore

### PR DESCRIPTION
**Pull request by bretwalker**

### CODE REVIEW

**Comment by thebouv** [comment]
Can you tell me why to do this?

I ask because it seems like convention is to version control the .ruby-version file if your application is a website, tool, etc.  But you don't check it in for a gem or library meant to run in multiple environments.

Is there a case for this website not to version control .ruby-version?

**Comment by bretwalker** [comment]
I just did it because I saw it locally and it wasn’t already in the repo and I assumed that was for a reason. I don’t know much about ruby development best practices.

**Comment by thebouv** [comment]
Ah, me either honestly.  I did a little research, but will ask @cheapwebmonkey too since she's more familiar with Ruby.

**Comment by bretwalker** [comment]
Cool. Maybe someone in the know can update the README with instructions for running locally. I had it running, but have no idea if I did it like a Ruby dev would have.

**Pull request closed without merging**
