### PR TITLE
Fixed jsonfeed.html layout

### PR DESCRIPTION
**Pull request by mgottholsen**
layout was not working properly due to commented code. Changed to pull blog posts instead of events.

### CODE REVIEW

**Comment by cheapwebmonkey** [comment]
I can check this out today/tonight

**Comment by cheapwebmonkey** [comment]
The code looks great!  

Could I please get clarification on what this addition gain us?  I'm not entirely clear on why we are adding this layout for blog posts, as blog posts are already handled nicely via Jekyll. In my head, they are anyway 😺 

I apologize for my obtuseness, it's been a long day

**Comment by mgottholsen** [comment]
No worries, JSON Feed is like a replacement for RSS, it's a newer spec for news reading

________________________________

**Comment by mgottholsen** [comment]
Check this out when you get a chance - https://jsonfeed.org/version/1

So basically it's lighter than RSS (as it's JSON), easier to develop against, and allows for more flexible changes over time.

**Comment by cheapwebmonkey** [comment]
What does this gain us vs leveraging github pages? https://help.github.com/articles/atom-rss-feeds-for-github-pages/

**Comment by cheapwebmonkey** [comment]
I’d like to hear Anthony’s thoughts on this. 

My instinct is to not add anything if we have the capability to accomplish the same end result by leveraging jekyll/githubpages, but I’m not a feed expert by any means.

**Comment by thebouv** [comment]
So, is this about us providing a json feed to people who want to consume it?  And we already provide an RSS feed, that we're switching out for this (or in addition to)?

Or is this about us consuming a json news feed instead of us consuming an RSS feed (I don't think this is it as I don't think we rely on RSS now).

But just getting clarification.

**Comment by mgottholsen** [comment]
Yes, it's about providing a more modern, flexible alternative to RSS, not consuming.

It's self documenting, supports images or other files, external urls, whether or not the content is html, and attachments w/ mimetypes. It also supports custom objects and podcasts.

So really, it's not meant to replace RSS (because it is a tried and true technology), but meant to be an enhancement alongside of it.

**Pull request merged**
